name: Continuous Integration - Dev

on:
  pull_request:
    branches:
      - github_actions
  push:
    branches:
      - github_actions

jobs:
  build_and_test:
    name: build and test

    strategy:
      matrix:
        os: [ubuntu-16.04]
        container: [ubuntu-16.04]
        go: [1.13]

    runs-on: ${{ matrix.os }}

    container:
      image: sylabsio/buildenv:${{ matrix.container }}-201910101738
      options: --privileged
      env:
        GO111MODULE: 'on'
        GOVERSION: ${{ matrix.go }}
        GOROOT: '/usr/local/go-${{ matrix.go }}'

    steps:
      - uses: actions/checkout@v1

      - name: Examine env
        run: |
          set -x
          pwd
          echo ========== CWD
          ls -l
          echo ========== /github/workspace
          ls -l /github/workspace || true
          echo ========== /github/home
          ls -l /github/home || true
          echo ========== /github/workflow
          ls -l /github/workflow || true
          echo ========== /mnt
          ls -l /mnt || true
          echo ========== /usr/local
          ls -l /usr/local/
          echo ========== /__w/
          ls -l /__w/
          df
          mount

  examine_vm:
    name: Examine VM

    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v1

      - name: Examine env
        run: |
          set -x
          ls -l '${{ runner.workspace }}'
          ls -l '${{ runner.temp }}'
          ls -l /mnt
          df
          mount
