name: Continuous Integration - Dev

on:
  pull_request:
    branches:
      - github_actions
  push:
    branches:
      - github_actions

jobs:
  build_and_test:
    name: build and test

    strategy:
      matrix:
        os: [ubuntu-16.04]
        container: [ubuntu-16.04]
        go: [1.13]

    runs-on: ${{ matrix.os }}

    container:
      image: sylabsio/buildenv:${{ matrix.container }}-201910101738
      options: --privileged --user 1001
      env:
        GO111MODULE: 'on'
        GOVERSION: ${{ matrix.go }}
        GOROOT: '/usr/local/go-${{ matrix.go }}'

    steps:
      - name: Add user
        run: |
          grep -q '^[^:]\+:[^:]\+:'$(id -u)':' /etc/passwd || sudo useradd --home-dir "$HOME" --uid $(id -u) --no-create-home runner

      - name: Check out code
        uses: actions/checkout@v1

      - name: Examine env
        run: |
          echo '========== env'
          env
          echo '========== id'
          id
          echo '========== pwd'
          pwd
          echo '========== ls -la'
          ls -la
          echo '========== ls -la /github/workspace'
          ls -la /github/workspace || true
          echo '========== ls -la /github/home'
          ls -la /github/home || true
          echo '========== ls -la /github/workflow'
          ls -la /github/workflow || true
          echo '========== ls -la /mnt'
          ls -la /mnt || true
          echo '========== ls -la /usr/local'
          ls -la /usr/local/ || true
          echo '========== ls -la /__w/'
          ls -la /__w/ || true
          echo '========== ls -la /github'
          ls -la /github || true
          echo '========== df'
          df
          echo '========== mount'
          mount

  examine_vm:
    name: Examine VM

    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v1

      - name: Examine env
        run: |
          echo '========== env'
          env
          echo '========== id'
          id
          echo '========== id 1001'
          id 1001 || true
          echo '========== pwd'
          pwd
          echo '========== ls -la'
          ls -la
          echo '========== ls -la ${{ runner.workspace }}'
          ls -la ${{ runner.workspace }} || true
          echo '========== ls -la $HOME'
          ls -la $HOME || true
          echo '========== ls -la /mnt'
          ls -la /mnt || true
          echo '========== df'
          df
          echo '========== mount'
          mount
          set -x
          df
          mount
