name: End-to-end testing - Dev

on:
  pull_request:
    branches:
      - github_actions
  push:
    branches:
      - github_actions

jobs:
  build_and_run_e2e:
    name: build and run E2E

    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        container: [ubuntu-16.04, ubuntu-18.04, centos-7, centos-8]
        go: [1.13]

    runs-on: ${{ matrix.os }}

    container:
      image: sylabsio/buildenv:${{ matrix.container }}-201910172051
      options: --privileged --user 1001
      env:
        GO111MODULE: 'on'
        GOVERSION: ${{ matrix.go }}
        GOROOT: '/usr/local/go-${{ matrix.go }}'
        PATH: '/usr/local/go-${{ matrix.go}}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Examine env
        run: |
          echo '========== env'
          env
          echo '========== id'
          id
          echo '========== pwd'
          pwd
          echo '========== ls -la'
          ls -la
          echo '========== ls -la /github/workspace'
          ls -la /github/workspace || true
          echo '========== ls -la /github/home'
          ls -la /github/home || true
          echo '========== ls -la /github/workflow'
          ls -la /github/workflow || true
          echo '========== ls -la /mnt'
          ls -la /mnt || true
          echo '========== ls -la /usr/local'
          ls -la /usr/local/ || true
          echo '========== ls -la /__w/'
          ls -la /__w/ || true
          echo '========== ls -la /github'
          ls -la /github || true
          echo '========== df'
          df
          echo '========== mount'
          mount
          echo '========== ps auxf'
          ps auxf

      - name: 'Initial setup'
        run: |
          test -e /etc/os-release && cat /etc/os-release
          # /tmp needs to be something that can be used as a overlayfs lowerdir
          sudo mount -t tmpfs tmpfs /tmp

      - name: 'Check go.mod'
        run: |
          scripts/check-go.mod

      - name: 'Configure'
        run: |
          ./mconfig -v --prefix="${RUNNER_TEMP}/s"

      - name: 'Code generation'
        run: |
          make -C builddir codegen

      - name: 'Build'
        run: |
          make -C builddir

      - name: 'Install'
        run: |
          sudo make -C builddir install

      - name: 'E2E tests'
        run: |
          make -C builddir e2e-test JUNIT_OUTPUT=yes
